- name: Enable container features
  poll: 0
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
